<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Game;

class GameSeeder extends Seeder
{
    public function run()
    {
        $games = [
            [
                'title' => 'Resident Evil 4 Remake',
                'description' => 'A survival horror remake where Leon S. Kennedy faces unimaginable terror in rural Europe.',
                'price' => 59.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6bo0.jpg',
                'platform' => 'PC, PS5, Xbox',
                'genre' => 'Survival Horror',
                'publisher' => 'Capcom',
                'release_date' => '2023-03-24',
            ],
            [
                'title' => 'Resident Evil Village',
                'description' => 'Ethan Winters returns in a horrifying journey through a mysterious village.',
                'price' => 49.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/coab9q.webp',
                'platform' => 'PC, PS5, Xbox',
                'genre' => 'Survival Horror',
                'publisher' => 'Capcom',
                'release_date' => '2021-05-07',
            ],
            [
                'title' => 'Mortal Kombat 11',
                'description' => 'The latest installment in the iconic brutal fighting franchise.',
                'price' => 39.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co20mh.webp',
                'platform' => 'PC, PS4, PS5, Xbox',
                'genre' => 'Fighting',
                'publisher' => 'Warner Bros. Games',
                'release_date' => '2019-04-23',
            ],
            [
                'title' => 'Mortal Kombat 1',
                'description' => 'A reborn Mortal Kombat universe created by Fire God Liu Kang.',
                'price' => 69.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9b8f.webp',
                'platform' => 'PC, PS5, Xbox',
                'genre' => 'Fighting',
                'publisher' => 'Warner Bros. Games',
                'release_date' => '2023-09-19',
            ],
            [
                'title' => 'The King of Fighters XV',
                'description' => 'Classic 3v3 fighting returns with modern visuals and netcode.',
                'price' => 59.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co6gt4.webp',
                'platform' => 'PC, PS4, PS5',
                'genre' => 'Fighting',
                'publisher' => 'SNK',
                'release_date' => '2022-02-17',
            ],
            [
                'title' => 'Devil May Cry 5',
                'description' => 'Stylish high-octane action with demon slaying and combo mastery.',
                'price' => 39.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1rb4.webp',
                'platform' => 'PC, PS5, Xbox',
                'genre' => 'Action',
                'publisher' => 'Capcom',
                'release_date' => '2019-03-08',
            ],
            [
                'title' => 'Ghost of Tsushima',
                'description' => 'An open-world samurai adventure set during the Mongol invasion of Japan.',
                'price' => 59.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2crj.jpg',
                'platform' => 'PS4, PS5',
                'genre' => 'Action Adventure',
                'publisher' => 'Sony Interactive Entertainment',
                'release_date' => '2020-07-17',
            ],
            [
                'title' => 'Red Dead Redemption 2',
                'description' => 'An epic tale of life in America’s unforgiving heartland.',
                'price' => 59.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1q1f.jpg',
                'platform' => 'PC, PS4, Xbox',
                'genre' => 'Open World',
                'publisher' => 'Rockstar Games',
                'release_date' => '2018-10-26',
            ],
            [
                'title' => 'Hogwarts Legacy',
                'description' => 'An immersive open-world RPG set in the Wizarding World.',
                'price' => 69.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/coaav6.webp',
                'platform' => 'PC, PS5, Xbox',
                'genre' => 'RPG',
                'publisher' => 'Warner Bros. Games',
                'release_date' => '2023-02-10',
            ],
            [
                'title' => 'Forza Horizon 5',
                'description' => 'An open-world racing game set in vibrant Mexico.',
                'price' => 59.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co3ofx.jpg',
                'platform' => 'PC, Xbox',
                'genre' => 'Racing',
                'publisher' => 'Xbox Game Studios',
                'release_date' => '2021-11-09',
            ],
            [
                'title' => 'God of War Ragnarök',
                'description' => 'Kratos and Atreus face the coming of Ragnarök.',
                'price' => 69.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5s5v.jpg',
                'platform' => 'PS5',
                'genre' => 'Action Adventure',
                'publisher' => 'Sony Interactive Entertainment',
                'release_date' => '2022-11-09',
            ],
            [
                'title' => 'The Witcher 3: Wild Hunt',
                'description' => 'A story-driven open-world RPG set in a dark fantasy universe.',
                'price' => 39.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1wyy.jpg',
                'platform' => 'PC, PS5, Xbox, Switch',
                'genre' => 'RPG',
                'publisher' => 'CD Projekt Red',
                'release_date' => '2015-05-19',
            ],
            [
                'title' => 'Elden Ring',
                'description' => 'A vast fantasy world filled with danger and discovery.',
                'price' => 59.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co4jni.jpg',
                'platform' => 'PC, PS5, Xbox',
                'genre' => 'Action RPG',
                'publisher' => 'Bandai Namco',
                'release_date' => '2022-02-25',
            ],
            [
                'title' => 'Final Fantasy VII Remake',
                'description' => 'A modern reimagining of a legendary RPG.',
                'price' => 59.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1qxr.webp',
                'platform' => 'PC, PS5',
                'genre' => 'RPG',
                'publisher' => 'Square Enix',
                'release_date' => '2020-04-10',
            ],
            [
                'title' => 'Assassin’s Creed Valhalla',
                'description' => 'Become a legendary Viking warrior.',
                'price' => 59.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2ed3.jpg',
                'platform' => 'PC, PS5, Xbox',
                'genre' => 'Action RPG',
                'publisher' => 'Ubisoft',
                'release_date' => '2020-11-10',
            ],
            [
                'title' => 'Sekiro: Shadows Die Twice',
                'description' => 'A brutal action-adventure set in feudal Japan.',
                'price' => 59.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co2a23.webp',
                'platform' => 'PC, PS4, Xbox',
                'genre' => 'Action',
                'publisher' => 'Activision',
                'release_date' => '2019-03-22',
            ],
            [
                'title' => 'Tekken 8',
                'description' => 'The next generation of legendary fighting game franchise.',
                'price' => 69.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co7lbb.webp',
                'platform' => 'PC, PS5, Xbox',
                'genre' => 'Fighting',
                'publisher' => 'Bandai Namco',
                'release_date' => '2024-01-26',
            ],
            [
                'title' => 'Street Fighter 6',
                'description' => 'A new evolution of the Street Fighter series.',
                'price' => 59.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co5vst.jpg',
                'platform' => 'PC, PS5, Xbox',
                'genre' => 'Fighting',
                'publisher' => 'Capcom',
                'release_date' => '2023-06-02',
            ],
            [
                'title' => 'Call of Duty: Modern Warfare III',
                'description' => 'The iconic FPS franchise returns with intense combat.',
                'price' => 69.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co1wkn.webp',
                'platform' => 'PC, PS5, Xbox',
                'genre' => 'FPS',
                'publisher' => 'Activision',
                'release_date' => '2023-11-10',
            ],
            [
                'title' => 'Grand Theft Auto V',
                'description' => 'A massive open-world crime game set in Los Santos.',
                'price' => 29.99,
                'cover_image' => 'https://images.igdb.com/igdb/image/upload/t_cover_big/co9751.webp',
                'platform' => 'PC, PS5, Xbox',
                'genre' => 'Open World',
                'publisher' => 'Rockstar Games',
                'release_date' => '2013-09-17',
            ],
        ];

        foreach ($games as $game) {
            Game::create($game);
        }
    }
}
